### 1. Write a NumPy program to test whether none of the elements of a given array is zero.

In [8]:
import numpy as np
def test_array_zeros(arr):
    return np.all(arr != 0)
arr = np.array([1, 2, 0, 4, 5,])
print(test_array_zeros(arr))

False


### 2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [1]:
import numpy as np
def test_array_nonzeros(arr):
   return np.count_nonzero(arr)
arr = np.array([0, 2, 0, 4, 5, 0])
print("No. of non zero elements is:",test_array_nonzeros(arr))

No. of non zero elements is: 3


### 3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [19]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1.0, 2.0, 3.0,20,10])
result = np.isclose(arr1, arr2, atol=1e-10)
print(result)
result = np.isclose(arr1, arr2,atol=0)
print(result)

[ True  True  True False False]
[ True  True  True False False]


### 4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [21]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


### 5. Write a NumPy program to create an array of the integers from 30 to70. 

In [22]:
import numpy as np
arr = np.arange(30, 71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


### 6. Write a NumPy program to create a 3x3 identity matrix

In [25]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 7. Write a NumPy program to generate a random number between 0 and 1

In [2]:
import numpy as np
print(np.random.rand())

0.22270481764037786


## 8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [4]:
import numpy as np
arr = np.random.normal(size=15)
print(arr)

[ 0.86733549 -0.47972228  0.48419614 -0.94882848 -0.18860707 -1.98772989
  0.61458148  1.84245769  0.61259811 -0.40023458 -0.63733028  0.36239318
  1.10393184  2.15229128 -0.88842721]


### 9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [6]:
import numpy as np
arr = np.arange(15, 56)
print(arr[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### 10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [12]:
import numpy as np
arr = np.random.randint(0, 11, 5)
print(arr)

[ 2  1  7  4 10]


### 11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [29]:
import numpy as np
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[-1, :] = 1
for i in range(1, 9):
    matrix[i, 0] = 1
    matrix[i, -1] = 1
for j in range(0, 9):
    matrix[0, j] = 1
    matrix[-1, j] = 1
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [31]:
import numpy as np
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix, np.arange(1, 6))
print(matrix)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


### 13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [33]:
import numpy as np
matrix = np.zeros((4, 4))
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
print(matrix)

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]


### 14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [35]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.savez('arrays.npz', arr1=arr1, arr2=arr2)
loaded_arrays = np.load('arrays.npz')
arr1_loaded = loaded_arrays['arr1']
arr2_loaded = loaded_arrays['arr2']
print('Array 1:', arr1_loaded)
print('Array 2:', arr2_loaded)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


### 15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [37]:
import numpy as np 
arr = np.random.rand(40)
print(arr)

[0.07751041 0.13638386 0.49291451 0.08248151 0.02697808 0.82220561
 0.24690611 0.52762137 0.25461878 0.47430435 0.84165504 0.6840024
 0.94208086 0.31709351 0.61926579 0.27788306 0.04724891 0.12067188
 0.57226744 0.82893414 0.43220283 0.98223391 0.59761903 0.85110343
 0.64868519 0.99357542 0.87348783 0.08240803 0.63849593 0.29672914
 0.14085588 0.4442242  0.40272636 0.76746385 0.99060204 0.92568769
 0.57665604 0.19908217 0.14066323 0.18450554]


### 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
num = 5
less_than_num = arr[arr < num]
greater_than_num = arr[arr > num]
print("Numbers less than", num, ":", less_than_num)
print("Numbers greater than", num, ":", greater_than_num)

Numbers less than 5 : [1 2 3 4]
Numbers greater than 5 : [ 6  7  8  9 10]
